### ISSUE TITLE
Click position is off

### ISSUE THREAD

**Issue by DrPandemic** [jaagr/polybar#246]
**Spec**
- polybar 2.3.5-2-g6f6c5b7-git
- Features: +alsa -i3 +mpd +network
- Cinnamon
- Arch
- Laptop

**Issue**
On my right bar, the click events seems not to be fired at the right place. The all seems off by some pixel to the left.

**Actual box**
![image](https://cloud.githubusercontent.com/assets/3250155/21249932/7e44f03c-c30f-11e6-9263-95ac679c7212.png)

**Expected**
![image](https://cloud.githubusercontent.com/assets/3250155/21249964/b73996cc-c30f-11e6-9713-fb8de034d7a7.png)

The ghost is a `menu`. I don't think I had this issue when I initially installed polybar.

My config can be found [here.](https://github.com/DrPandemic/dotfiles/blob/master/polybar/config)

**Comment by jaagr** [comment]
This has been fixed, update to a newer version

**Comment by DrPandemic** [comment]
Sorry for that, I thought I did my updates before posting... Thank you for your time.

**Comment by DrPandemic** [comment]
I just did the update to `polybar 2.3.13` and I still have the same issue

**Comment by jaagr** [comment]
Yeah,  the commit 4c2d710 is not in a release tag yet
