### ISSUE TITLE
Unable to launch example bar

### ISSUE THREAD

**Issue by Goodpie** [jaagr/polybar#254]
I'm unable to launch the example bar.

After running `make userconfig` and modifying the config to use my current monitor then running `polybar example`, I get the following output:

```
polybar example
terminate called after throwing an instance of 'xpp::x::error::name'
  what():  XCB_NAME (15)
Aborted (core dumped)
```

**Comment by jaagr** [comment]
What version are you running? `polybar -vv`

**Comment by Goodpie** [comment]
`polybar -vv`

```
polybar 2.3.13 

Features: -alsa +i3 -mpd -network 

Build type: Release
Compiler flags:  -Wall -Wextra -Werror -O3 -pedantic -pedantic-errors -ffunction-sections -fdata-sections
Linker flags:  -Wl,--gc-sections

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

**Comment by jaagr** [comment]
Could you try building against master?

**Comment by Goodpie** [comment]
Having a few issues rebuilding

I've run 

```
make uninstall
make clean
```

and when building again, at 20% (`[ 20%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o`)

I get the following:

```
In file included from /home/brandyn/Documents/source/polybar/src/drawtypes/animation.cpp:1:
In file included from /home/brandyn/Documents/source/polybar/include/drawtypes/animation.hpp:6:
In file included from /home/brandyn/Documents/source/polybar/include/components/config.hpp:2:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/unordered_map:47:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/hashtable.h:35:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/hashtable_policy.h:85:11: error: implicit instantiation
      of undefined template 'std::hash<polybar::v2_0_0::edge>'
        noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/type_traits:138:14: note: in instantiation of template class
      'std::__detail::__is_noexcept_hash<polybar::v2_0_0::edge, std::hash<polybar::v2_0_0::edge> >' requested here
    : public conditional<_B1::value, _B2, _B1>::type
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/type_traits:148:39: note: in instantiation of template class
      'std::__and_<std::__is_fast_hash<std::hash<polybar::v2_0_0::edge> >, std::__detail::__is_noexcept_hash<polybar::v2_0_0::edge,
      std::hash<polybar::v2_0_0::edge> > >' requested here
    : public integral_constant<bool, !_Pp::value>
                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/unordered_map.h:46:34: note: in instantiation of template
      class 'std::__not_<std::__and_<std::__is_fast_hash<std::hash<polybar::v2_0_0::edge> >,
      std::__detail::__is_noexcept_hash<polybar::v2_0_0::edge, std::hash<polybar::v2_0_0::edge> > > >' requested here
           typename _Tr = __umap_traits<__cache_default<_Key, _Hash>::value>>
                                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/unordered_map.h:100:15: note: in instantiation of default
      argument for '__umap_hashtable<polybar::v2_0_0::edge, polybar::v2_0_0::border_settings, std::hash<polybar::v2_0_0::edge>,
      std::equal_to<polybar::v2_0_0::edge>, std::allocator<std::pair<const polybar::v2_0_0::edge, polybar::v2_0_0::border_settings> >
      >' required here
      typedef __umap_hashtable<_Key, _Tp, _Hash, _Pred, _Alloc>  _Hashtable;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/brandyn/Documents/source/polybar/include/components/types.hpp:118:45: note: in instantiation of template class
      'std::unordered_map<polybar::v2_0_0::edge, polybar::v2_0_0::border_settings, std::hash<polybar::v2_0_0::edge>,
      std::equal_to<polybar::v2_0_0::edge>, std::allocator<std::pair<const polybar::v2_0_0::edge, polybar::v2_0_0::border_settings> >
      >' requested here
  std::unordered_map<edge, border_settings> borders{};
                                            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/system_error:134:12: note: template is declared here
    struct hash;
           ^
In file included from /home/brandyn/Documents/source/polybar/src/drawtypes/animation.cpp:1:
In file included from /home/brandyn/Documents/source/polybar/include/drawtypes/animation.hpp:6:
In file included from /home/brandyn/Documents/source/polybar/include/components/config.hpp:2:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/unordered_map:48:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/unordered_map.h:522:7: error: multiple overloads of
      'erase' instantiate to the same signature 'iterator (iterator)'
      erase(iterator __position)
      ^
/home/brandyn/Documents/source/polybar/include/components/types.hpp:118:45: note: in instantiation of template class
      'std::unordered_map<polybar::v2_0_0::edge, polybar::v2_0_0::border_settings, std::hash<polybar::v2_0_0::edge>,
      std::equal_to<polybar::v2_0_0::edge>, std::allocator<std::pair<const polybar::v2_0_0::edge, polybar::v2_0_0::border_settings> >
      >' requested here
  std::unordered_map<edge, border_settings> borders{};
                                            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.2.1/../../../../include/c++/5.2.1/bits/unordered_map.h:517:7: note: previous declaration is here
      erase(const_iterator __position)
      ^
2 errors generated.
bin/CMakeFiles/polybar.dir/build.make:307: recipe for target 'bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o' failed
make[2]: *** [bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o] Error 1
CMakeFiles/Makefile2:314: recipe for target 'bin/CMakeFiles/polybar.dir/all' failed
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
** Failed to build project
```

**Comment by jaagr** [comment]
Yeah, I've fixed that but haven't pushed my changes yet. Will ping you when it's ready.

**Comment by Goodpie** [comment]
Cheers

**Comment by jaagr** [comment]
You could apply this patch (`man git-apply`) until I've pushed my changes (alot of cleanup so might take a while):

~~~ diff
diff --git a/include/components/types.hpp b/include/components/types.hpp
index 0271ec9..cb75132 100644
--- a/include/components/types.hpp
+++ b/include/components/types.hpp
@@ -8,6 +8,13 @@
 
 POLYBAR_NS
 
+struct enum_hash {
+  template <typename T>
+  inline typename std::enable_if<std::is_enum<T>::value, size_t>::type operator()(T const value) const {
+    return static_cast<size_t>(value);
+  }
+};
+
 enum class edge : uint8_t { NONE = 0U, TOP, BOTTOM, LEFT, RIGHT, ALL };
 
 enum class alignment : uint8_t { NONE = 0U, LEFT, CENTER, RIGHT };
@@ -115,7 +122,7 @@ struct bar_settings {
   line_settings underline{};
   line_settings overline{};
 
-  std::unordered_map<edge, border_settings> borders{};
+  std::unordered_map<edge, border_settings, enum_hash> borders{};
 
   uint8_t spacing{1U};
   string separator{};
~~~

**Comment by Goodpie** [comment]
Still getting errors

```
[ 29%] Building CXX object bin/CMakeFiles/polybar.dir/components/eventloop.cpp.o
/home/brandyn/Documents/source/polybar/src/components/eventloop.cpp:244:20: error: no viable conversion from
      'const polybar::v2_0_0::eventloop::event' to 'uint8_t' (aka 'unsigned char')
  const event quit{static_cast<const event>(*evt())};
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/brandyn/Documents/source/polybar/src/components/eventloop.cpp:257:22: error: no viable conversion from
      'const polybar::v2_0_0::eventloop::event' to 'uint8_t' (aka 'unsigned char')
    const event quit{reinterpret_cast<const event&>(*evt())};
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/brandyn/Documents/source/polybar/src/components/eventloop.cpp:265:16: error: no viable conversion from
      'const polybar::v2_0_0::eventloop::event' to 'uint8_t' (aka 'unsigned char')
  event update{reinterpret_cast<const event&>(*evt())};
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/brandyn/Documents/source/polybar/src/components/eventloop.cpp:276:15: error: no viable conversion from
      'const polybar::v2_0_0::eventloop::event' to 'uint8_t' (aka 'unsigned char')
  event check{reinterpret_cast<const event&>(*evt())};
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
bin/CMakeFiles/polybar.dir/build.make:468: recipe for target 'bin/CMakeFiles/polybar.dir/components/eventloop.cpp.o' failed
make[2]: *** [bin/CMakeFiles/polybar.dir/components/eventloop.cpp.o] Error 1
CMakeFiles/Makefile2:314: recipe for target 'bin/CMakeFiles/polybar.dir/all' failed
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
** Failed to build project
```

I'll wait for you to push out the changes

**Comment by jaagr** [comment]
Could you try with the latest changes

**Comment by Goodpie** [comment]
Working now. Thank you!

**Comment by roberoonska** [comment]
I'm having this same problem. Output is:
```
terminate called after throwing an instance of 'xpp::x::error::name'
  what():  XCB_NAME (15)
Aborted (core dumped)
```
And here is the output for my version:
```
polybar 2.4.6 

Features: +alsa +curl +i3 +mpd +network 

Build type: Release
Compiler: /usr/bin/c++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```
