### ISSUE TITLE
Click error

### ISSUE THREAD

**Issue by Soulhub** [jaagr/polybar#268]
Nothing happens when clicking on clickable areas. Running polybar in terminal and attempting to click, I get this message `warn: Uncaught input event, forwarding to shell... (input: )` and no other output. Polybar version is 2.4.1 (polybar-git 2.4.1.r1.g7ecd132-1 on Arch Linux).

**Comment by jaagr** [comment]
1cb8e45 should fix this issue, please verify

**Comment by japhir** [comment]
Yes, the latest updates fix the issue for me.

**Comment by Soulhub** [comment]
Now it seems to work fine for the most part but the same error persists when clicking on the workspaces area (internal/bspwm module). Scrolling works for changing workspace but clicking doesn't.

On a side note, do I have to use some specific syntax for running commands with arguments when clicking on a module? For example, I can run `termite` but `termite -e tmux` outputs error.

**Comment by jaagr** [comment]
@Soulhub: Could you paste `polybar -vv` ?

What error are you getting? It works fine for me using:
~~~ dosini
click-left = termite -e tmux &
~~~

Don't forget to end with `&` otherwise the bar will wait for the command to end before continuing execution.

**Comment by Deluxo** [comment]
Still can't L-Click the bspwm workspaces...

**Comment by jaagr** [comment]
@Deluxo `polybar -vv`?

**Comment by Soulhub** [comment]
polybar -vv output:
`polybar 2.4.2

Features: +alsa +curl -i3 +mpd +network

Build type: Release
Compiler: /usr/sbin/g++
Compiler flags:  -Wall -Wextra -Werror -O3 -pedantic -pedantic-errors -ffunction-sections -fdata-sections
Linker flags:  -Wl,--gc-sections

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp`

Errors about termite:
`warn: Uncaught input event, forwarding to shell... (input: cite -e tmux &)`
`warn: Uncaught input event, forwarding to shell... (input: *bite -e tmux &)`

Errors when clicking on bspwm workspaces:
`warn: Uncaught input event, forwarding to shell... (input: em-deskfocus0+1)`
`warn: Uncaught input event, forwarding to shell... (input: <am-deskfocus0+1)`
And sometimes after that I get either 1 or 127 exit status.

**Comment by jaagr** [comment]
Could you try rebuilding the package

**Comment by Soulhub** [comment]
I just did (version 2.4.2-1-g70bb6f6-git) and I get the same errors. I don't know if it helps you in any way but the last working version for me was 2.3.13.

**Comment by jaagr** [comment]
I was able to reproduce it on my arch laptop. Will ping you when I got it fixed.

**Comment by jaagr** [comment]
@Soulhub the issue has been fixed. Could you please verify

**Comment by Soulhub** [comment]
Can confirm. Version is 2.4.3-1-gbb0d6f5-git and everything works as expected.

Thank you very much for your quick response and your effort in general. You sir have my humble gratitude.

**Comment by jaagr** [comment]
@Soulhub Thanks man, appreciate it!

**Comment by notantonia** [comment]
Hey, I'm getting the same error here. Happens with both polybar and polybar-git (from AUR), which are polybar 2.4.3 and polybar 2.4.3-18-g18cf9df-git

example:

```
[module/test]
type = custom/text
content = test
click-left = echo left
```

clicking other things, like the date module and i3 workspaces works fine however.

**Comment by jaagr** [comment]
@notantonia your config probably works fine but the echo left is just echoed into the void..

**Comment by notantonia** [comment]
ah, I see! thanks

**Comment by wjgan7** [comment]
Hi, it's been a long time since this issue was closed but for some reason L-click doesn't work for me right now. I can use scroll wheel to cycle between my workspaces but if I click on the icon for a specific one nothing happens. I believe I have the latest version of polybar installed and my config used to work on a different setup but now it doesn't.

I'm a bit of an newbie when it comes to all things Linux so I'm not sure what info to post but I can upload anything. My distro is Ubuntu.

[Here's a picture of my bar](https://i.imgur.com/chIOg28.png)
