### ISSUE TITLE
Bar overlaps fullscreen applications when `override-redirect` is true

### ISSUE THREAD

**Issue by zhiayang** [jaagr/polybar#293]
So, after some searching I came across https://www.reddit.com/r/unixporn/comments/5jdzqi/how_does_one_create_a_centered_polybar_with, and did that.

So I'm getting a non-full-width centred bar on the bottom of my screen now. I'm using `width = 85%; offset-x = 7.5%; override-redirect = true` .

As the issue suggests however, the bar is showing up on top of fullscreen windows such as youtube on firefox.

I've tried a combination of `dock = true`, `wm-restack = i3`, as well as `override-redirect = true`, to no avail. Curiously, if I have `wm-restack = i3`, but nothing else (ie. `dock = false` and `override-redirect = false`), the bar is no longer centred on the bottom,  but is now hidden in fullscreen apps.

What's going on? The config for the bar is below:

```
[bar/bottom]
width = 85%
offset-x = 7.5%
height = 30
offset-y = 0
bottom = true

# override-redirect = true

;background = ${xrdb:color9}
background = ${colors.background}
foreground = ${colors.foreground}

overline-size = 0
overline-color = #f00
underline-size = 0
underline-color = #00f

border-bottom = 0
border-bottom-color = ${colors.background}

spacing = 1
padding-left = 5
padding-right = 5
module-margin-left = 1
module-margin-right = 2

# font-0 = hack:pixelsize=12;0
font-0 = Dejavu Sans:pixelsize=13;1
font-1 = unifont:size=6:heavy:fontformat=truetype;-2
font-2 = siji:pixelsize=10;0
font-3 = FontAwesome:pixelsize=14;0
font-4 = Termsynu:size=8;-1


modules-left = mpd
modules-center = i3
modules-right = temperature padding-small cpu padding-small memory

wm-restack = i3
# dock = true
```

**Comment by jaagr** [comment]
The `dock` parameter has been replaced by `override-redirect` so you can remove it.

`override-redirect = true` is required with i3 if you want to control the size/position of the bar.

`wm-restack = i3` should be used together with `override-redirect = true`... it has no effect otherwise (as stated by the warning message printed if they are mixed)

`bottom = true/false` is not related to this... it just sets the base position

**Comment by zhiayang** [comment]
OK, so now i have `override-redirect = true`, and `wm-restack = i3`. Position is centred, but it still shows up on top of fullscreen applications.

**Comment by jaagr** [comment]
I checked the source and you need to define `monitor = <output>` when using the restacking with i3

**Comment by jaagr** [comment]
How are you launching the bar?

**Comment by jaagr** [comment]
I was using `i3-gaps`. Tried with `i3` and noticed that the bar gets moved up in the stack whenever a workspace is created.

**Comment by jaagr** [comment]
could you try with the patch 2ebaa0f

**Comment by zhiayang** [comment]
I'm using i3-gaps. I have this in my config, somewhere near the bottom:
`exec_always --no-startup-id "$HOME/.config/polybar/startup.sh"`

The script is as such:
```
#!/usr/bin/env sh

# kill existing
killall -q polybar

# wait until they die of blood loss
while pgrep -x polybar >/dev/null; do sleep 1; done

# launch the 2 bars
polybar top &
polybar bottom &
```

I did end up setting the monitor variable, in my case `monitor = "HDMI-0"`

**Comment by zhiayang** [comment]
Alright, the new patch seems to have fixed it -- thanks!

**Comment by jaagr** [comment]
Great

**Comment by zhiayang** [comment]
Hi sorry to be a bother again, but it's not completely fixed, it appears. If I restart i3 in-place in, for example, workspace 2, and fullscreen something that was originally in that workspace, the bar disappears as expected.

However, if I restart i3 in while in workspace 1, then either (a) move the application from WS2 to WS1, or switch to WS2 and attempt to fullscreen, the bar remains visible.

**Comment by zhiayang** [comment]
Ok, looks like it's properly fixed now. Thanks!

**Comment by thyeun** [comment]
Sorry everyone, i still having issue with this once i change `override-redirect = true`, 

bar still overlaps fullscreen

Below is my code
```
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/i3/polybar/colors
include-file = ~/.config/i3/polybar/modules
include-file = ~/.config/i3/polybar/decor
include-file = ~/.config/i3/polybar/system

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false

override-redirect = true

bottom = true
fixed-center = false

width = 90%
height = 15

offset-x = 1.5%
offset-y = 1%

background = #16161E
foreground = ${color.foreground}

radius-top = 0.0
radius-bottom = 0.0

line-size = 0
line-color = ${color.blue}

border-size = 0
border-color = ${color.background}

padding = 0

module-margin-left = 0
module-margin-right = 0

font-0 = "Source Code Pro Medium:size=8;4"
font-1 = "Iosevka Nerd Font:size=10;3"
font-2 = "Iosevka Nerd Font:size=12;3"
font-3 = "Iosevka Bold:size=12;3"
font-4 = "Noto Sans Mono CJK TC:size=7;2"
font-5 = "Noto Sans Mono CJK SC:size=7;2"
font-6 = "Source Code Pro Medium:size=6;2"

# Default
# modules-left = spacing BLD launcher BRD dot GLD cpu YPL memory CPL filesystem CRD dot MLD network MRD
##modules-left = spacing BLD launcher BRD dot LD i3 RD
modules-left = i3 
# modules-center = LD xwindow RD
modules-center = xwindow
# modules-right = RLD battery RRD dot GLD volume YPL brightness YRD dot BLD time BRD spacing
##modules-right = MLD network MRD dot GLD volume YPL brightness YRD dot BLD time BRD spacing

spacing = 0
dim-value = 1.0

tray-position = none
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

enable-ipc = true

cursor-click = 
cursor-scroll = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]
throttle-output = 5
throttle-output-for = 10

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
```

**Comment by evilenzo** [comment]
> And if i include `wm-restack = i3`, the bar always behind my eww-bar, and no way it will appear above eww-bar.

Same thing

**Comment by thyeun** [comment]
@evilenzo i got the solution, but you will only using eww-bar with include ```workspace```

**Comment by patrick96** [comment]
> And if i include wm-restack = i3, the bar always behind my eww-bar, and no way it will appear above eww-bar.

That's what `wm-restack` does. It puts polybar behind all other windows.

**Comment by Jimmytalksalot** [comment]
> could you try with the patch [2ebaa0f](https://github.com/polybar/polybar/commit/2ebaa0fb5fa5834f5bf90e155c699aff534bc14f)

how the heck do I add a patch to polybar? I thought it was simple and easy to use.

**Comment by Jimmytalksalot** [comment]
> > And if i include wm-restack = i3, the bar always behind my eww-bar, and no way it will appear above eww-bar.
> 
> That's what `wm-restack` does. It puts polybar behind all other windows.

is this really supposed to help.

**Comment by Jimmytalksalot** [comment]
when I disable i3 restack, polybar appears over windows, but I want to appear below, and on the top of windows, without touching the windows.
