### ISSUE TITLE
Trying to display certain characters crashes polybar

### ISSUE THREAD

**Issue by d125q** [jaagr/polybar#602]
Trying to display certain characters (e.g., opening [this link](https://zhuanlan.zhihu.com/p/26871672) on Firefox and using the `xwindow` module) crashes polybar.  This likely depends on the font being used -- in my case that's [Iosevka](https://github.com/be5invis/Iosevka).

**Comment by raidzero** [comment]
That link works fine with my font (DejaVu Sans) and yours. My xwindow module config looks like this:

`[module/xwindow]
pin-output = false (ignore this, it has not been merged in yet - PR open)
type = internal/xwindow
format-underline = #00000000
format-foreground = ${colors.primary}
label = %title:0:75:...%
`

**Comment by jaagr** [comment]
What version are you using? (`polybar -vv`)

**Comment by d125q** [comment]
```txt
polybar 3.0.1-6-gaf64c48

Features: +alsa +curl -i3 -mpd +network

X extensions: +randr (+monitors) -render -damage -sync -composite +xkb +xrm

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Werror -O2 -pedantic -pedantic-errors
Linker flags: 

ALSA_SOUNDCARD              default
BSPWM_SOCKET_PATH           /tmp/bspwm_0_0-socket
BSPWM_STATUS_PREFIX         W
BUILDER_SPACE_TOKEN         %__
CONNECTION_TEST_IP          8.8.8.8
PATH_ADAPTER                /sys/class/power_supply/%adapter%
PATH_BACKLIGHT_MAX          /sys/class/backlight/%card%/max_brightness
PATH_BACKLIGHT_VAL          /sys/class/backlight/%card%/brightness
PATH_BATTERY                /sys/class/power_supply/%battery%
PATH_CPU_INFO               /proc/stat
PATH_MEMORY_INFO            /proc/meminfo
PATH_TEMPERATURE_INFO       /sys/class/thermal/thermal_zone%zone%/temp
```

```conf
[module/xwindow]
type				= internal/xwindow
label				= %title:0:50:...%
label-underline			= ${colors/light.orange}
```

**Comment by jaagr** [comment]
You're using an old version. Update to the latest version because this should already be fixed.

**Comment by d125q** [comment]
I *am* using the latest version, and the issue is still present.

**Comment by jaagr** [comment]
According to the output you posted you're not.

**Comment by d125q** [comment]
Then what *is* the latest version?  I have installed `polybar` via [polybar-git](https://aur.archlinux.org/packages/polybar-git/) from the AUR.

**Comment by jaagr** [comment]
`3.0.5`
